name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Build and test
        env:
          DEBUG: 'zarro::'
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          SUPPRESS_DOWNLOAD_PROGRESS: 1
        run: |
          npm i
          npm run test-ci-windows
          
      - name: Upload build reports    
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: buildreports/
          
  test-linux:
    # disabled, for now, because it hangs
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: 🥜 Check out project
      uses: actions/checkout@v4
    - name: ⬆️ Fetch latest software lists
      run: |
        sudo apt update -q

    - name: 🟥 Setup Redis
      run: |
        sudo apt install redis-server -q

    - name: ⚙️ Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          7.x

    - name: 🟢 Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: 🏗️ Build and test everything EXCEPT TempDb 🧪
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        SUPPRESS_DOWNLOAD_PROGRESS: 1
      run: |
        npm i
        npm run test-not-tempdb

    - name: 🏗️ Build and test TempDb 🧪
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        SUPPRESS_DOWNLOAD_PROGRESS: 1
      run: |
        npm run test-ci-tempdb

    - name: 📃 Upload build report
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: buildreports/
